{% set name = "stone" %}
{% set version = "3.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dropbox/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 21434d0872bae54da77aef0f2233161218a2dde77777452c3f08f5c83102fa53

build:
  number: 0
  noarch: python
  entry_points:
    - stone=stone.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ==5.2.0
    - python >=3.5
  run:
    - ply >=3.4
    - python >=3.5
    - six >=1.12.0

test:
  imports:
    - stone
    - stone.backends
  commands:
    - pip check
    - stone --help
    - pytest test
  requires:
    - pip
    - pytest <5
    - mock>=2.0.0,<5.0
    - coverage==5.3
  source_files:
    - test

about:
  home: https://www.dropbox.com/developers
  summary: Stone is an interface description language (IDL) for APIs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/stone
  doc_url: https://github.com/dropbox/stone/tree/main/docs

extra:
  recipe-maintainers:
    - cjmartian
    - BastianZim
