{% set name = "stone" %}
{% set version = "3.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dropbox/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 273a2ab461356513914852005fbf10f49bda3a03082f58f3b352c7a7f250a97a

build:
  number: 0
  noarch: python
  entry_points:
    - stone=stone.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ==5.3.2
    - python >=3.5
  run:
    - ply >=3.4
    - python >=3.5
    - six >=1.12.0

test:
  imports:
    - stone
  commands:
    - pip check
    - stone --help
  requires:
    - pip

about:
  home: https://www.dropbox.com/developers
  summary: Stone is an interface description language (IDL) for APIs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/stone
  doc_url: https://github.com/dropbox/stone/tree/main/docs

extra:
  recipe-maintainers:
    - cjmartian
    - BastianZim
