{% set name = "stone" %}
{% set version = "3.3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dropbox/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e9a54a81208ac2f3724523c3007492ad3cdb9b6a3eb69ad0d3eac94b1a2e0d69

build:
  number: 0
  noarch: python
  entry_points:
    - stone=stone.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ==5.3.2
    - python {{ python_min }}
  run:
    - jinja2 >=3.0.3
    - packaging >=21.0
    - ply >=3.4
    - python >={{ python_min }}
    - six >=1.12.0

test:
  imports:
    - stone
  commands:
    - pip check
    - stone --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.dropbox.com/developers
  summary: Stone is an interface description language (IDL) for APIs.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/stone
  doc_url: https://github.com/dropbox/stone/tree/main/docs

extra:
  recipe-maintainers:
    - cjmartian
    - BastianZim
